# Generated by Django 4.2.3 on 2023-08-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0008_alter_roomtype_description'),
        ('issue_notice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantnotice',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.property'),
        ),
    ]
