# Generated by Django 4.2.3 on 2023-08-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_notice_app', '0002_alter_tenantnotice_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantnotice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
