# Generated by Django 5.0 on 2023-12-16 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsCredential",
            fields=[
                ("api", models.TextField()),
                ("username", models.CharField(max_length=100)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="client_app.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("api", "client")},
            },
        ),
    ]
