# Generated by Django 4.2.4 on 2023-10-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsCredential",
            fields=[
                ("api", models.TextField()),
                ("username", models.CharField(max_length=100)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="client_app.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("api", "client")},
            },
        ),
    ]
