# Generated by Django 4.2.3 on 2023-08-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_remove_client_added_by'),
        ('sms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscredential',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.client', unique=True),
        ),
    ]
