# Generated by Django 4.2.3 on 2023-08-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_remove_client_added_by'),
        ('sms_api', '0002_alter_smscredential_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscredential',
            name='id',
        ),
        migrations.AlterField(
            model_name='smscredential',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client_app.client'),
        ),
    ]
