# Generated by Django 4.2.3 on 2023-08-01 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_app', '0002_remove_client_added_by'),
        ('property_app', '0008_alter_roomtype_description'),
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client_app.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.property'),
        ),
    ]
