# Generated by Django 5.0 on 2023-12-16 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("property_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermapping",
            name="property_linked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property_app.property"
            ),
        ),
        migrations.AddField(
            model_name="usermapping",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermapping",
            unique_together={("user", "property_linked")},
        ),
    ]
