# Generated by Django 4.2.4 on 2023-10-23 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("property_app", "0001_initial"),
        ("client_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermapping",
            name="property_linked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property_app.property"
            ),
        ),
        migrations.AddField(
            model_name="usermapping",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="client_app.client"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermapping",
            unique_together={("user", "property_linked")},
        ),
    ]
