# Generated by Django 4.2.3 on 2023-07-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='propertyy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
