# Generated by Django 4.2.3 on 2023-08-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0008_alter_roomtype_description'),
        ('authentication', '0005_usermapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermapping',
            old_name='property',
            new_name='property_linked',
        ),
        migrations.AlterUniqueTogether(
            name='usermapping',
            unique_together={('user', 'property_linked')},
        ),
    ]
