# Generated by Django 4.2.4 on 2023-12-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_remove_client_added_by'),
        ('authentication', '0006_rename_property_usermapping_property_linked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.client'),
        ),
    ]
