# Generated by Django 4.2.3 on 2023-07-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='county',
        ),
        migrations.RemoveField(
            model_name='property',
            name='street',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='Roysa', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='Kenya', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='town',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
    ]
