# Generated by Django 4.2.3 on 2023-07-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_remove_property_county_remove_property_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='town',
            field=models.CharField(max_length=255),
        ),
    ]
