# Generated by Django 4.2.3 on 2023-07-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0003_alter_property_address_alter_property_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
