# Generated by Django 4.2.3 on 2023-07-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0006_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='client',
        ),
    ]
