# Generated by Django 4.2.3 on 2023-07-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0007_remove_roomtype_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
