# Generated by Django 4.2.4 on 2023-10-23 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tenant_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property_app", "0001_initial"),
        ("client_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=255)),
                ("alternative_names", models.CharField(blank=True, null=True)),
                ("id_number", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_of_lease", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=10,
                    ),
                ),
                (
                    "deposit_amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "date_of_deposit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("next_of_kin", models.CharField(blank=True, null=True)),
                ("next_of_kin_contact", models.CharField(blank=True, null=True)),
                (
                    "intro_by",
                    models.CharField(
                        choices=[("Self", "Self"), ("Agent", "Agent")],
                        default="Self",
                        max_length=5,
                    ),
                ),
                ("agent_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "agent_phone",
                    tenant_app.models.KenyanPhoneNumberField(
                        blank=True, max_length=13, null=True
                    ),
                ),
                (
                    "agent_id_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "agent_commission",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "agent_trasaction_ref",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client_app.client",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property_app.property",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property_app.room",
                    ),
                ),
            ],
        ),
    ]
