# Generated by Django 4.2.3 on 2023-08-02 17:06

from django.db import migrations
import tenant_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=tenant_app.models.KenyanPhoneNumberField(max_length=13),
        ),
    ]
