# Generated by Django 4.2.3 on 2023-08-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0002_alter_tenant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_of_lease',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='next_of_kin',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='alternative_names',
            field=models.CharField(blank=True, null=True),
        ),
    ]
