# Generated by Django 4.2.3 on 2023-08-06 19:59

from django.db import migrations
import tenant_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0004_tenant_agent_commission_tenant_agent_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='next_of_kin_contact',
            field=tenant_app.models.KenyanPhoneNumberField(blank=True, max_length=13, null=True),
        ),
    ]
