# Generated by Django 4.2.3 on 2023-08-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0005_tenant_next_of_kin_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='next_of_kin_contact',
        ),
    ]
