# Generated by Django 4.2.4 on 2023-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0007_tenant_next_of_kin_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='date_of_deposit',
            field=models.DateTimeField(default='2023-08-16'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
