# Generated by Django 4.2.3 on 2023-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0009_alter_tenant_date_of_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_deposit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
