# Generated by Django 4.2.3 on 2023-08-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='date_of_payment',
            field=models.DateField(default='2022-02-02'),
        ),
    ]
