# Generated by Django 4.2.3 on 2023-08-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_alter_paymenttransaction_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='date_of_payment',
            field=models.DateField(default='2023-02-02'),
        ),
    ]
