# Generated by Django 4.2.3 on 2023-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_alter_paymenttransaction_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='date_of_payment',
            field=models.DateField(),
        ),
    ]
